CREATE TABLE "pg-drizzle_match" (
	"id" integer PRIMARY KEY NOT NULL,
	"nextMatchId" integer,
	"nextLooserMatchId" integer,
	"tournamentRoundText" varchar(256) NOT NULL,
	"state" varchar(256) NOT NULL,
	"team1Id" integer,
	"team2Id" integer,
	"winnerId" integer,
	"is_loser_bracket" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_team" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pg-drizzle_team_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_match" ADD CONSTRAINT "pg-drizzle_match_team1Id_pg-drizzle_team_id_fk" FOREIGN KEY ("team1Id") REFERENCES "public"."pg-drizzle_team"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_match" ADD CONSTRAINT "pg-drizzle_match_team2Id_pg-drizzle_team_id_fk" FOREIGN KEY ("team2Id") REFERENCES "public"."pg-drizzle_team"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_match" ADD CONSTRAINT "pg-drizzle_match_winnerId_pg-drizzle_team_id_fk" FOREIGN KEY ("winnerId") REFERENCES "public"."pg-drizzle_team"("id") ON DELETE no action ON UPDATE no action;